In [1]:
!python --version

Python 3.14.0

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Job_2_resource_Weather_Test_Data.csv")

In [5]:
df.head(5)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Row0,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No
1,Row1,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No
2,Row2,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,24.0,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No
3,Row3,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,28.0,42.0,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No
4,Row4,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,28.0,76.0,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42677 entries, 0 to 42676
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row ID         42677 non-null  object
 1   Location       42677 non-null  object
 2   MinTemp        42483 non-null  float64
 3   MaxTemp        42585 non-null  float64
 4   Rainfall       42250 non-null  float64
 5   Evaporation    24365 non-null  float64
 6   Sunshine       22178 non-null  float64
 7   WindGustDir    39868 non-null  object
 8   WindGustSpeed  39887 non-null  float64
 9   WindDir9am     39670 non-null  object
 10  WindDir3pm     41547 non-null  object
 11  WindSpeed9am   42264 non-null  float64
 12  WindSpeed3pm   41882 non-null  float64
 13  Humidity9am    42136 non-null  float64
 14  Humidity3pm    41573 non-null  float64
 15  Pressure9am    38411 non-null  float64
 16  Pressure3pm    38432 non-null  float64
 17  Cloud9am       26592 non-null  float64
 18  Cloud3pm       25585 non-null  float64
 19  Temp9am        42387 non-null  float64
 20  Temp3pm        41855 non-null  float64
 21  RainToday      42250 non-null  object
dtypes: float64(16), object(6)
memory usage: 7.2+ MB

In [9]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,42483.000000,42585.000000,42250.000000,24365.000000,22178.000000,39887.000000,42264.000000,41882.000000,42136.000000,41573.000000,38411.000000,38432.000000,26592.000000,25585.000000,42387.000000,41855.000000
mean,12.210032,23.246068,2.342862,5.489715,7.647831,40.001379,13.995315,18.607516,68.791176,51.597672,1017.581591,1015.192792,4.412041,4.466054,17.028266,21.700982
std,6.432122,7.123596,8.412106,4.248850,3.778019,13.605915,8.872445,8.806916,18.996115,20.844525,7.094070,7.016408,2.887927,2.729640,6.501771,6.951426
min,-8.200000,-4.800000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000,1.000000,1.000000,982.200000,977.100000,0.000000,0.000000,-7.200000,-5.400000
25%,7.600000,18.000000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.800000,21.100000
75%,16.900000,28.300000,0.600000,7.400000,10.700000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.500000
max,31.800000,47.000000,278.400000,145.000000,14.300000,122.000000,74.000000,83.000000,100.000000,100.000000,1040.400000,1038.900000,8.000000,8.000000,39.400000,45.400000

In [10]:
df.shape

(42677, 22)

In [11]:
df.isnull().sum()

row ID               0
Location             0
MinTemp            194
MaxTemp             92
Rainfall           427
Evaporation      18312
Sunshine         20499
WindGustDir       2809
WindGustSpeed     2790
WindDir9am        3007
WindDir3pm        1130
WindSpeed9am       413
WindSpeed3pm       795
Humidity9am        541
Humidity3pm       1104
Pressure9am       4266
Pressure3pm       4245
Cloud9am         16085
Cloud3pm         17092
Temp9am            290
Temp3pm            822
RainToday          427
dtype: int64

In [12]:
df.dropna(inplace=True)

In [13]:
df.isnull().sum()

row ID           0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
dtype: int64

In [14]:
df.shape

(16846, 22)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.head(5)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
1756,Row1787,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0,SSE,...,19.0,30.0,8.0,1012.9,1012.1,1.0,1.0,20.3,27.0,No
1757,Row1788,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0,NNE,...,15.0,42.0,22.0,1012.3,1009.2,1.0,6.0,28.7,34.9,No
1758,Row1789,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0,WNW,...,6.0,37.0,22.0,1012.7,1009.1,1.0,5.0,29.1,35.6,No
1759,Row1790,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0,NW,...,13.0,19.0,15.0,1010.7,1007.4,1.0,6.0,33.6,37.6,No
1760,Row1791,Cobar,19.7,35.5,0.0,11.0,12.7,NE,41.0,NNE,...,17.0,61.0,14.0,1007.9,1005.8,1.0,5.0,24.0,33.6,No

In [17]:
df.sample(10)

,row ID,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
18973,Row19401,MelbourneAirport,5.1,13.6,3.4,2.6,7.3,N,57.0,N,...,33.0,81.0,76.0,1016.1,1013.8,1.0,7.0,7.2,10.9,Yes
35362,Row36234,Perth,12.5,25.6,0.0,7.8,12.6,SW,31.0,SSW,...,17.0,57.0,38.0,1015.4,1013.2,0.0,0.0,20.9,24.6,No
25105,Row25793,Brisbane,21.1,30.6,0.0,8.4,11.5,ENE,24.0,SE,...,15.0,63.0,56.0,1015.9,1012.6,3.0,1.0,27.2,29.1,No
34602,Row35474,PerthAirport,22.8,35.6,0.0,11.0,11.2,E,76.0,NE,...,20.0,51.0,16.0,1013.4,1010.3,1.0,1.0,28.4,35.0,No
25834,Row26525,Cairns,22.2,30.8,10.8,3.8,7.3,NNE,31.0,SE,...,13.0,68.0,72.0,1009.8,1006.4,6.0,5.0,28.0,29.3,Yes
37955,Row38886,Hobart,13.0,18.7,0.0,9.2,9.1,WNW,50.0,NNE,...,17.0,48.0,60.0,1005.0,1005.2,3.0,4.0,18.1,16.8,No
9377,Row9571,Sydney,10.5,19.3,0.0,3.4,2.3,W,26.0,WNW,...,13.0,87.0,70.0,1025.8,1021.6,8.0,7.0,11.7,18.3,No
13591,Row13948,Canberra,3.9,13.5,0.2,2.0,8.9,WNW,46.0,NNW,...,20.0,68.0,53.0,1019.2,1018.0,3.0,4.0,9.5,11.6,No
40511,Row41448,AliceSprings,12.4,18.5,0.0,7.6,8.5,ESE,52.0,ESE,...,30.0,44.0,22.0,1027.7,1023.5,7.0,7.0,13.1,17.8,No
18393,Row18819,Sale,9.0,15.1,0.4,2.6,1.9,W,72.0,W,...,43.0,62.0,70.0,1003.9,1004.9,7.0,5.0,13.0,13.5,No

In [18]:
df.select_dtypes(include="object").columns

Index(['row ID', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm',
       'RainToday'],
      dtype='object')

In [19]:
len(df.select_dtypes(include="object").columns)

6

In [20]:
df = df.drop(columns=["row ID"], errors="ignore")

In [21]:
len(df.select_dtypes(include="object").columns)

5

In [22]:
df.select_dtypes(include="object").columns

Index(['Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday'], dtype='object')